'''
Configuration parameters
'''

TX_PER_BLOCK = 100
TX_MAX_PAY = 1000
DIFFICULTY = 5
TX_DIFFICULTY = 4
VOTE_DIFFICULTY = 4
NODES_PER_SHARD = 1
SHARD_NUM = 20
TOTAL_NUMBER_OF_NODES = NODES_PER_SHARD * SHARD_NUM
BLOCKS_NUMBER = 40
BLOCK_LIMITS = 17